### ISSUE TITLE
[Feature Request]: Create a launchpad home page

### ISSUE THREAD

**Issue by atapas** [CreoWis/next-js-launchpad#10]
### Feature details

It will be great to create a launch pad home page and use that rather than having the default Next.js initial page.

### Suggested Solution

It can have the information that we have in the readme.. like:

- Purpose
- Tech involved
- How to get started.
- A footer talk about Open SOurce from CreoWis

It should be a very lightweight page without spending too much time on it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Vijaykv5** [comment]
I'm interested go give it a try!
