### ISSUE TITLE
🐛 [Bug report]: Missing eslintignore file

### ISSUE THREAD

**Issue by joypoddar** [CreoWis/next-js-launchpad#18]
### Describe the bug?

.eslintignore file is missing which is causing an error while running lint task

### Steps to reproduce the bug?

Go to terminal 
run `npm run lint-prettier`

### Expected behavior

The above command should run and give possible lint errors if any

### Solution 
* create `.eslintignore` file under root
Paste the following contents inside the file
```
dist/*
.cache
public
node_modules
*.esm.js
```
Go to `package.json` and change the existing line to below
`"lint-prettier": "npm run lint:check && npm run prettier:check"`

### Desktop (Please provide your system information)

OS: UBUNTU
Browser: Chrome
Version: Version 121.0.6167.139 (Official Build) (64-bit)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rick799** [comment]
I am interested in this issue. Please assign it to me.
